### ISSUE TITLE
No eu-north-1 AWS region.

### ISSUE THREAD

**Issue by Mathisco-01** [Arattian/DynamoDb-GUI-Client#67]
**Describe the bug**
My dynamoDB is hosted in Stockholm (eu-north-1), and when adding a new database, there is no eu-north-1 option.

**To Reproduce**
Click on add database. Under AWS region you can see there is no option for eu-north-1.

**Expected behavior**
I expected there to be an option for eu-north-1.

**Screenshots**
[imgur img](https://i.imgur.com/HDVWr1B.png)

**Desktop (please complete the following information):**
 - OS: pop!_os
 - Browser Firefox
 - Version V2.1.1

**Comment by lannsjo** [comment]
Anyone fixed this yet?

**Comment by mathisve** [comment]
Yes it is! 
Has been fixed since [this PR](https://github.com/Arattian/DynamoDb-GUI-Client/commit/256a8e43f035f7efdf8a2d37bd2960550a81bbaf). Not sure why they didn't mention this issue in the commit.
Although if you want to use it you'll have to build the app yourself (which doesn't even work for me) because the latest release is more than a year old.
So you're better off just using AWS's [NoSQL Workbench](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/workbench.settingup.html).
